# Generated by Django 4.2.2 on 2024-10-06 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_booking_amount_booking_order_id_booking_pay_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='order_id',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='booking',
            name='razorpay_id',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
