# Generated by Django 4.2.2 on 2024-10-06 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_booking_order_id_alter_booking_razorpay_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='order_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='p_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='booking',
            name='razorpay_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
